### ISSUE TITLE
BLE branch install and runtime dependencies

### ISSUE THREAD

**Issue by Jc2k** [jlusiardi/homekit_python#106]
The BLE branch introduces new dependencies, at install time and again at runtime.

I think the new install time dependencies should be optional. I think we should do this with `extras_require` in setup.py, see [here](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies).

Then we should see what happens on a mac if you try and run the ip controller. I Imagine the imports that are missing will go pop. So we should be able to do tricks like just-in-time imports or something like:

``` 
try:
    import dbus
except ImportError:
    dbus = None
```

You should be able to still pair and interact with an IP accessory from a mac after merging the BLE branch.

**Comment by jlusiardi** [comment]
`extra_require` does not help during installing via `pip` but I think I will give it a try 👍🏼

The second block looks interesting but we shouldn’t have those all over the code I guess

**Comment by Jc2k** [comment]
It should help with pip as well. You would be able to do pip install homekit[ble].

**Comment by Jc2k** [comment]
And yeah, we dont want try/except imports everywhere. We can probably contain it to a few places so it’s not too ugly.

**Comment by jlusiardi** [comment]
Yay got it. Using pip to install this package doesn’t rely on requirements.txt. But is this file then needed at all?

**Comment by Jc2k** [comment]
The thing I always bring out when this comes up is a blog post by one of the pypi maintainers:

https://caremad.io/posts/2013/07/setup-vs-requirement/

You are right, a library doesn't strictly need a requirements.txt, and all being well `pip install -e .` in a virtualenv is the same (if not better than) a `pip install -r requirements.txt`.

There might be some value in having a requirements.txt for a dev or test environment, but it would only be for people working on the library. I'm not sure it buys us much.

**Comment by jlusiardi** [comment]
This could also solve the issues with different operating systems, when BLE support is only available on Linux? Could make a ticket for non-linux platforms obsolete (see https://github.com/jlusiardi/homekit_python/issues/104#issuecomment-463091030).

**Comment by Jc2k** [comment]
Ahh I did actually raise *this* ticket for the non-Linux platforms :) so there is no other ticket I plan to open about it 👍🏻

**Comment by jlusiardi** [comment]
d'oh ;)

**Comment by jlusiardi** [comment]
I did some work on this in https://github.com/jlusiardi/homekit_python/tree/fix_106_install_and_runtime_dependencies

What do you think?

**Comment by Jc2k** [comment]
Looking good!

Re: 8ae8fe4dcec332348d9ce6b813083954f5ed2085 - this actually makes our cryptography dependency >=2.5 instead of >=2. I checked in HA - thats OK from my point of view, HA upgraded last week. But I thought i'd highlight it - we should bump setup.py to >=2.5.

It's annoying that we can't drop the cairo dep + gtk deps. I might have to try and reach out to them about it if it complicates the eventual HA setup.

Other than that, 👍

**Comment by jlusiardi** [comment]
ah, yes right, forgot about cryptography 2.5. I did 8ae8fe4 because it complained about deprecation with the used version. I'll update in setup.py & requirements.txt.

Regarding the other dependencies, should we pinpoint at least the major versions for now?

And set some python minimum version? Perhaps 3.3, I am pretty sure 2.x does not work.

**Comment by Jc2k** [comment]
RE: python version - definitely no need to support 2.x at this point, I agree i don't think it would work. HA only supports 3.5 and later, so thats the only versions I strongly care about. I am interested in trying to add some asyncio stuff in the future, which I believe is easier if targetting 3.5 and later.

Looking at distro versions:

 * Alpine 3.8 - python 3.6.6
 * Alpine 3.9 - python 3.6.8
 * Debian Jessie (oldstable) - 3.4.2 
 * Debian Stretch (stable) - 3.5.3
 * Debian Buster (currently in beta) - 3.7.2
 * Ubuntu 14.04 (2 LTS ago) - 3.4.0
 * Ubuntu 16.04 (1 LTS ago) - 3.5.1
 * Ubuntu 18.04 (current LTS) - 3.6.5
 * Ubuntu 19.04 (next non-LTS) - 3.7.2
 * Raspbian - based on stretch, so 3.5.3.
 * Mac - no 3.x by default, i have 3.6 and 3.7 via brew.sh
 * Fedora 29 - 3.7.2
 * Fedora 28 - 3.6.8

Struggling to find RHEL/CentOS versions, but they normally have ancient versions and everyone uses supplementary yum repos to fill in the gaps.

RE: dependency versions - i'm not too worried about having a loose set of dependencies. Python does a really crap job of enforcing them anyway (i've seen collisions in large requirements.txt that don't trigger errors, just 1 line warnings in the middle of vast pip install logs).

**Comment by jlusiardi** [comment]
Ok, so we should agree on 3.5 onwards which would
- be good enough for Home Assistant 
- cover most of the current linux distributions

Since 3.5, 3.6 and 3.7 seem to be in use under linux, I should have automatic tests for them.
Perhaps also integrate OS X with at least 3.5.

**Comment by Jc2k** [comment]
Sounds good to me 👍

**Comment by jlusiardi** [comment]
Just making some experiments to also have windows as test platform.

**Comment by jlusiardi** [comment]
ok, i think this is done
