### ISSUE TITLE
Problem with Xiaomi Aqara gateway and lowercase service and characteristics UUID's

### ISSUE THREAD

**Issue by quarcko** [jlusiardi/homekit_python#108]
There was big update in Home Assistant homekit controller component,
and now the problem that was badly patched by me in 'get_short' making UUID .upper()
does not help anymore, as there is now need to have '.upper()' in also 'get_uuid'
method - which can accept both short uuid or string name (so cannot make upper there)...

I am not very good at python, nor know your library well, but i have an idea
maybe you can point me out the necessary file to tinker with:

Lets solve this problem and the core - which file is responsible for getting those UUID's from homekit protocol (https?)?
maybe it is feasible to make them .upper() right there and then there will be no need
to patch holes in rest of the code.

**Comment by jlusiardi** [comment]
Hi,
i hoped we had fixed the issue in #101. What commands did you execute and can you `--log DEBUG`?
Greetings
Joachim

**Comment by quarcko** [comment]
Problem is not with your command line tools (which still work fine), but in the Home Assistant,
which uses your library to communicate to Homekit devices. Specifically this file is making use
of 'get_short' and after last update also 'get_uuid' was added to the mix:

https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/homekit_controller/__init__.py

Of course i could try to push the changes directly to their file, but i think that this 
issue should be solved at library level.

**Comment by jlusiardi** [comment]
@Jc2k can you help here?

**Comment by quarcko** [comment]
Sorted.
Please review my PR, now it is "true" fix and controller.py level.
All 'types' are converted to uppercase for all devices.

So it should work now for your own command line tools as well as for external users like HA.

**Comment by quarcko** [comment]
P.S.
could you make a release of lib before HA 0.89 cycle starts?
Would like to see this merged there

**Comment by Jc2k** [comment]
My config flow branch of HA actually does some fixes on the HA side for this, but I think your PR is the right way.

We should do it for characteristics too. Both type fields should be normalised to upper case full uuids wherever possible.

**Comment by quarcko** [comment]
So far this fix just does uppercasing, conversion to full UUID is missing,
need to check if rest of library will be able to operate after such conversion.

**Comment by jlusiardi** [comment]
@quarcko can you add conversion to full UUIDs?

**Comment by quarcko** [comment]
Done.

**Comment by jlusiardi** [comment]
@quarcko just merged! Congrats ;)

**Comment by quarcko** [comment]
Thank you for helping out with this patch :)
When is planned next release? hope to hit HA soon... :)

closing.

**Comment by jlusiardi** [comment]
perhaps I could do it into a 0.12.3 next week, but not sure when. I am a little busy currently.
