### ISSUE TITLE
Factor out discover_homekit_devices into helper function

### ISSUE THREAD

**Issue by Jc2k** [jlusiardi/homekit_python#117]
HA uses its own zeroconf discovery. It would be good to be aple to reuse the logic in `discover_homekit_devices` for parsing the properties data it discovers.

(This came up in a code review in HA where i'm handling the pairing status flags).

(I plan to try and look at this myself but is there a branch you'd prefer to see it on?)

**Comment by jlusiardi** [comment]
As for the branch: this has nothing todo with bluetooth, right? So just branch of master. I have a precondition that must hold: the project must be usable without hass.io (and keep integratable with others)

**Comment by Jc2k** [comment]
Sure. I all I plan to do is split `discover_homekit_devices` into 2 functions - the behaviour will be unchanged for `discover_homekit_devices`. But the new function will take a dictionary of properties HA has found and do the same normalisation homekit_python does with its discovery code. It's important that this library works standalone.

Branchwise - I agree it should be fine on `master`, i just am extremely nervous about making changes on master that make it harder to merge with `add_bluetooth` later. I've had very bad experiences with long lived branches in previous $DAYJOBs and don't want to make it harder for you!

**Comment by jlusiardi** [comment]
i have to admit, i am not so experienced with merging and see this more as a challenge 😉

**Comment by Jc2k** [comment]
Haha 😂

**Comment by Jc2k** [comment]
Closing because change merged.
