### ISSUE TITLE
Unknown error on initial pair setup

### ISSUE THREAD

**Issue by mjg59** [jlusiardi/homekit_python#12]
Trying to pair with an Ikea Tradfri running the latest (Homekit-compatible) firmware:

Step #3: unkown error

Packet dump of the transaction attached
[pairing.zip](https://github.com/jlusiardi/homekit_python/files/1800986/pairing.zip)

**Comment by mjg59** [comment]
I've previously played with a couple of Homekit devices that were very picky about header ordering, so I don't know if that could be contributing. I don't have a convenient iOS device - I'll try to find one so I can see what the functioning pairing looks like

**Comment by mjg59** [comment]
Ok, that doesn't seem to be it - sending an apparently identical request using curl (mocking up the same headers and ordering gives a more reasonable response.
[pairing3.zip](https://github.com/jlusiardi/homekit_python/files/1801009/pairing3.zip)

**Comment by jlusiardi** [comment]
i just looked into your dump of pairing3. 
Apple's spec says TLV items for state (M1) and method (Pair Setup) must be 
transmitted. I am not sure if the ordering of the TLV items is relevant. Can
you try to send 
`0x06 0x01 0x01 0x00 0x01 0x01`

instead of

`0x00 0x01 0x01 0x06 0x01 0x01`?

Perhaps i missed that in the documentation or IKEA Tradfi just relies on it.

**Comment by mjg59** [comment]
The problem is because http.client (in 3.5, at least) sends the headers and the body as separate packets, and this device mishandles the case. Monkey-patching http.client to send in a single packet fixes it.

**Comment by jlusiardi** [comment]
is this something to be fixed within this project?

**Comment by mjg59** [comment]
I don't think it can easily be fixed there, but I'll think about it some more

**Comment by nickpl456** [comment]
@mjg59 I'm running into this issue as well on a Leviton switch, could you give some detail on what you had to "monkey-patch"? (can't say I've heard that term before, I'm not much of a programer though :) )

**Comment by mjg59** [comment]
@nickpl456 Monkey Patching in Python refers to replacing a method in an imported module with your own method. In Home Assistant I have this:

```
def homekit_http_send(self, message_body=None, encode_chunked=False):
    r"""Send the currently buffered request and clear the buffer.

    Appends an extra \r\n to the buffer.
    A message_body may be specified, to be appended to the request.
    """
    self._buffer.extend((b"", b""))
    msg = b"\r\n".join(self._buffer)
    del self._buffer[:]

    if message_body is not None:
        msg = msg + message_body

    self.send(msg)
```

and then later do:

```
        http.client.HTTPConnection._send_output = homekit_http_send
```

to replace the _send_output function with my own. If you do that at the start of your code you ought to be able to get further.

**Comment by jlusiardi** [comment]
I just tried to fix the issue without changing the behavior of the original `http.client.HTTPConnection` for all the code running in the interpreter. what do you think about  61bf4e9 ?

**Comment by nickpl456** [comment]
Just tested out 61bf4e9 and it works great, I'm able to successfully pair with and control my Leviton switch, thanks guys!

**Comment by mjg59** [comment]
I think you need to add an extra (and unused) named argument for 3.6 compatibility - see https://github.com/mjg59/home-assistant/commit/705b430671896722132c1887659c0e82032f8836

**Comment by mjg59** [comment]
(But otherwise this looks good!)

**Comment by jlusiardi** [comment]
thanks for the hint for python 3.6 @mjg59. So either way of patching this will be an ongoing process, I guess.

**Comment by jlusiardi** [comment]
I would close this as done then.
