### ISSUE TITLE
Tradfri doesn't respond to encrypted messages

### ISSUE THREAD

**Issue by mjg59** [jlusiardi/homekit_python#13]
After monkey patching http.client to avoid https://github.com/jlusiardi/homekit_python/issues/12 I can successfully pair my Tradfri, but any packet sent after switching to SecureHttp never receives a response.

**Comment by jlusiardi** [comment]
can you attach the dump? afair the stuff was pretty picky about keeping the connection open...

**Comment by mjg59** [comment]
[get_accessories.zip](https://github.com/jlusiardi/homekit_python/files/1821352/get_accessories.zip)

Interesting - there does seem to be a response, but we're never doing anything with it. I'll dig further.

**Comment by mjg59** [comment]
Oh right the response is just the ack, ignore me. I've also tried adding a Host: header to the request, since that seemed to be the only difference to what an iOS device seems to be sending at this point.

**Comment by jlusiardi** [comment]
The get_accessories dump seems odd. This should contain 0x06 for kTLVType_State somewhere?

**Comment by mjg59** [comment]
It looks like there's an 0x06 TLV at the end of each POST to pair-verify, and one at the end of each response?

**Comment by mjg59** [comment]
Ah - SecureHttp isn't changing \n to \r\n

**Comment by mjg59** [comment]
Yes, adding
 	data = data.replace("\n", "\r\n")
to the top of _handle_request() makes this work

**Comment by mjg59** [comment]
https://github.com/jlusiardi/homekit_python/pull/14

**Comment by jlusiardi** [comment]
so you get progress on the tradfri, any success in switching it on and off?

**Comment by mjg59** [comment]
I'm using Hue bulbs, and it turns out that the Tradfri will only expose Ikea bulbs over Homekit :( I suspect it'd work fine now, I'm able to read the accessory-info characteristics.
