### ISSUE TITLE
Will you support add pairings?

### ISSUE THREAD

**Issue by a3135134** [jlusiardi/homekit_python#144]
Will you support add pairings?

**Comment by jlusiardi** [comment]
Hi,

Add pairing (as of chapter 4.11 of the spec) might be implemented. But the first step involves some out-of-band  mechanism, which is not described. This mechanism must provide

- AdditionalControllerPairingIdentifier
- AdditionalControllerLTPK

I have no clue on how this out-of-band mechanism  works for iOS devices. 

What kind of controllers do you want to add?

**Comment by a3135134** [comment]
Hello,
As a first step, I think it would be good to provide methods implementing AddPairings and provide a class to generate AdditionalControllerPairingIdentifier and AdditionalControllerLTPK as a demo.  

I want to control HAP device on different clients, but the device can only be paired with one controller. Could you provide some clues to implement this function? I can do it myself. I believe this project already implemented related functions generating ControllerPairingIdentifier and AdditionalControllerLTPK. 

In addition, I think it would be better to use requests library to replace httpconnection in http layer for better performance. Because http.client can't enforce the persistent connection.

**Comment by jlusiardi** [comment]
hey,

i did some work in branch `fix_144_add_pairings`, perhaps you can have a look?

One thing is still missing: 
remove_pairing command can only remove the pairing over which one connects to the accessory. This is bad because non-admin pairings cannot remove themselves. I am on this issue.

**Comment by a3135134** [comment]
> 
> 
> hey,
> 
> i did some work in branch `fix_144_add_pairings`, perhaps you can have a look?
> 
> One thing is still missing:
> remove_pairing command can only remove the pairing over which one connects to the accessory. This is bad because non-admin pairings cannot remove themselves. I am on this issue.

A non-admin user cannot remove pairings according to spec in section 4.12.  So it's not necessary to implement that.

**Comment by jlusiardi** [comment]
Yes that is correct. But if a admin user adds a non-admin user and removes the admin pairing after that, the non-admin user can use the accessory but cannot add or remove pairings anymore.

**Comment by a3135134** [comment]
> 
> 
> Yes that is correct. But if a admin user adds a non-admin user and removes the admin pairing after that, the non-admin user can use the accessory but cannot add or remove pairings anymore.

No. This situation is also considered in spec. If an accessory does not have a admin-user, it will remove all users. So you don't need to worry about that.

**Comment by jlusiardi** [comment]
can you have a look if the code from the branch https://github.com/jlusiardi/homekit_python/tree/fix_144_add_pairings fulfills the requirements?

**Comment by jlusiardi** [comment]
Meanwhile I merge into master.

**Comment by a3135134** [comment]
Thanks. I see.
I believe it would be decent.
