### ISSUE TITLE
Issues with pairing LIFXZ LED strip

### ISSUE THREAD

**Issue by netmanchris** [jlusiardi/homekit_python#145]
Looking for troubleshooting steps here

I can see this device
```
Name: LifX Strip Top._hap._tcp.local.
Url: http_impl://10.101.30.60:80
Configuration number (c#): 3
Feature Flags (ff): Supports HAP Pairing (Flag: 1)
Device ID (id): B6:1B:12:3E:43:B2
Model Name (md): LIFX Z
Protocol Version (pv): 1.1
State Number (s#): 1
Status Flags (sf): Accessory has not been paired with any controllers. (Flag: 1)
Category Identifier (ci): Lightbulb (Id: 5)
```
When I attempt to add this device using the following command
```
python3 -m homekit.pair -d B6:1B:12:3E:43:B2 -p 555-55-555 -a strip -f lifx2
```

The function appears to finish with the following response
```
step 5
```

Unfortunately, there's nothing in the lifx2 database. 

I would appreciate pointers on how to troubleshoot this! 

thanks!

**Comment by jlusiardi** [comment]
hey,

can you tell me which version of homekit_python you are using? 
Can you rerun the pairing with a `--log debug` and post the output?

regards
Joachim

**Comment by netmanchris** [comment]
Sorry!  

Version 0.14.0

Here's the debug

```
2019-07-05 17:56:27,122 __init__.py:0106 DEBUG #1 ios -> accessory: send SRP start request
2019-07-05 17:56:27,122 tlv.py:0134 DEBUG sending [
  6: (1 bytes) 0x01
  0: (1 bytes) 0x01
]

2019-07-05 17:56:27,123 tlv.py:0117 DEBUG receiving [
  6: (1 bytes) 0x01
  0: (1 bytes) 0x01
]

2019-07-05 17:56:27,123 __init__.py:0060 DEBUG write message: [
  6: (1 bytes) 0x01
  0: (1 bytes) 0x01
]

2019-07-05 17:56:35,217 tlv.py:0117 DEBUG receiving [
  6: (1 bytes) 0x02
  3: (384 bytes) 0x7a5d388addb0fbe0a3fc0ea02ebfa7855a1d0eecb7fd9dcde6d973270cade9bb79606e6c47c95f9ac1c35d89364066b244734f4e4db3d3d784a40004392997cf96f2a4e13bbdafe71903375661786d5d975675db8dd684374d50cf931d139968ff908a730979641a5ef7ef7b37bcc011fae51c6bd5b1c0c7e179073af643b40d605256e128b1efd68762549928056fc1a31319eb473b48171bdb3791261166aaa158f203bc1da037b9d3220bb12ec148a0e5341f6df3c2ec739fc8c1c259ad9d58ad62832d7f13f117bba2dc78dfa80b4a58b50871927adef6d67bde404e2376eef96ea294ad5ba18cf030928c11f22d818192c39fa111df1f40912aa6fce2f88cd36c3f854517110db6cc1fa86c4434b31773f84358e77ef45a7d6b0e993c2eb69bde5ab059b6ad7b2d349c716185e6c38132b96d4bd561749fd2a35c7bd6961b33734ddf93c1cdf8c257e5709fb0b02400e837943eea46508e4f32b0afa989ebdb082f6500d391578f3e308a69559d712051ec98d1da8595e2b57b526d6f47
  2: (16 bytes) 0x00000000000000000000000000000000
]

2019-07-05 17:56:35,225 __init__.py:0067 DEBUG response: [
  6: (1 bytes) 0x02
  3: (384 bytes) 0x7a5d388addb0fbe0a3fc0ea02ebfa7855a1d0eecb7fd9dcde6d973270cade9bb79606e6c47c95f9ac1c35d89364066b244734f4e4db3d3d784a40004392997cf96f2a4e13bbdafe71903375661786d5d975675db8dd684374d50cf931d139968ff908a730979641a5ef7ef7b37bcc011fae51c6bd5b1c0c7e179073af643b40d605256e128b1efd68762549928056fc1a31319eb473b48171bdb3791261166aaa158f203bc1da037b9d3220bb12ec148a0e5341f6df3c2ec739fc8c1c259ad9d58ad62832d7f13f117bba2dc78dfa80b4a58b50871927adef6d67bde404e2376eef96ea294ad5ba18cf030928c11f22d818192c39fa111df1f40912aa6fce2f88cd36c3f854517110db6cc1fa86c4434b31773f84358e77ef45a7d6b0e993c2eb69bde5ab059b6ad7b2d349c716185e6c38132b96d4bd561749fd2a35c7bd6961b33734ddf93c1cdf8c257e5709fb0b02400e837943eea46508e4f32b0afa989ebdb082f6500d391578f3e308a69559d712051ec98d1da8595e2b57b526d6f47
  2: (16 bytes) 0x00000000000000000000000000000000
]

2019-07-05 17:56:35,228 __init__.py:0118 DEBUG #3 ios -> accessory: send SRP verify request
2019-07-05 17:56:35,311 tlv.py:0134 DEBUG sending [
  6: (1 bytes) 0x03
  3: (384 bytes) 0x70fa4bcbd8a1e3c3cc1fd6e218f9db55013ea2a7198bc64ffa62b381ad9ecdb37bccb222d87cd4b3e25961ac863c12997c93e7e214bcb13340dbb841ebc763e1965a0205bdf7d4f42e873cada9ada8b4d80721a7ab00e6ba07f5458e416b98c73161de023899628b138963eb4b26a868f6989245403f380e05dd03e56f57827f6e0e4c3ca9d52cb27076e4e1f7bd4cb7528342ffd6692685225d39c831296008d4cf4830f4b556b8cf0e2c964bfe34f605c7c396c14e633e0366eaddde2824768f08893b05431751a5d9f4fd330123554b5f5a3d04072c3903e1c783a0ecf957c7326cf266595cbc05746254350e157e92ab026aa7347ab4777286d9cc3d1e8ee24dcfceda379294ba9a3782109ac7d52e16564be6d43f62b2bfdc382054cda53a17612e2dabc96359a535b02019c924d0d39877a996cdc741fc076002c9397910b225644f158e3028dc0f3542e776e41da9bb773913fa119ee91e353f32d3c03296ffd3ac7a3e0b13ce4bdcd5ebb2a79d64465cb1d267099ee27f36a5f4e209
  4: (64 bytes) 0xa0337d9e9a1af722af472e07eb30ef661a3ba35c421bd7d0b3b4cc3526042c71d2ccf5926ad0d8d44a732bf1908bd57104c8befd7085c55126deeaf8f9dd7697
]

2019-07-05 17:56:35,312 tlv.py:0117 DEBUG receiving [
  6: (1 bytes) 0x03
  3: (384 bytes) 0x70fa4bcbd8a1e3c3cc1fd6e218f9db55013ea2a7198bc64ffa62b381ad9ecdb37bccb222d87cd4b3e25961ac863c12997c93e7e214bcb13340dbb841ebc763e1965a0205bdf7d4f42e873cada9ada8b4d80721a7ab00e6ba07f5458e416b98c73161de023899628b138963eb4b26a868f6989245403f380e05dd03e56f57827f6e0e4c3ca9d52cb27076e4e1f7bd4cb7528342ffd6692685225d39c831296008d4cf4830f4b556b8cf0e2c964bfe34f605c7c396c14e633e0366eaddde2824768f08893b05431751a5d9f4fd330123554b5f5a3d04072c3903e1c783a0ecf957c7326cf266595cbc05746254350e157e92ab026aa7347ab4777286d9cc3d1e8ee24dcfceda379294ba9a3782109ac7d52e16564be6d43f62b2bfdc382054cda53a17612e2dabc96359a535b02019c924d0d39877a996cdc741fc076002c9397910b225644f158e3028dc0f3542e776e41da9bb773913fa119ee91e353f32d3c03296ffd3ac7a3e0b13ce4bdcd5ebb2a79d64465cb1d267099ee27f36a5f4e209
  4: (64 bytes) 0xa0337d9e9a1af722af472e07eb30ef661a3ba35c421bd7d0b3b4cc3526042c71d2ccf5926ad0d8d44a732bf1908bd57104c8befd7085c55126deeaf8f9dd7697
]

2019-07-05 17:56:35,313 __init__.py:0060 DEBUG write message: [
  6: (1 bytes) 0x03
  3: (384 bytes) 0x70fa4bcbd8a1e3c3cc1fd6e218f9db55013ea2a7198bc64ffa62b381ad9ecdb37bccb222d87cd4b3e25961ac863c12997c93e7e214bcb13340dbb841ebc763e1965a0205bdf7d4f42e873cada9ada8b4d80721a7ab00e6ba07f5458e416b98c73161de023899628b138963eb4b26a868f6989245403f380e05dd03e56f57827f6e0e4c3ca9d52cb27076e4e1f7bd4cb7528342ffd6692685225d39c831296008d4cf4830f4b556b8cf0e2c964bfe34f605c7c396c14e633e0366eaddde2824768f08893b05431751a5d9f4fd330123554b5f5a3d04072c3903e1c783a0ecf957c7326cf266595cbc05746254350e157e92ab026aa7347ab4777286d9cc3d1e8ee24dcfceda379294ba9a3782109ac7d52e16564be6d43f62b2bfdc382054cda53a17612e2dabc96359a535b02019c924d0d39877a996cdc741fc076002c9397910b225644f158e3028dc0f3542e776e41da9bb773913fa119ee91e353f32d3c03296ffd3ac7a3e0b13ce4bdcd5ebb2a79d64465cb1d267099ee27f36a5f4e209
  4: (64 bytes) 0xa0337d9e9a1af722af472e07eb30ef661a3ba35c421bd7d0b3b4cc3526042c71d2ccf5926ad0d8d44a732bf1908bd57104c8befd7085c55126deeaf8f9dd7697
]

2019-07-05 17:56:38,164 tlv.py:0117 DEBUG receiving [
  6: (1 bytes) 0x04
  7: (1 bytes) 0x02
]

2019-07-05 17:56:38,164 __init__.py:0067 DEBUG response: [
  6: (1 bytes) 0x04
  7: (1 bytes) 0x02
]

2019-07-05 17:56:38,164 __init__.py:0169 DEBUG #5 ios -> accessory: send SRP exchange request
step 5
2019-07-05 17:56:38,164 pair.py:0085 DEBUG step 5
Traceback (most recent call last):
  File "/Users/christopheryoung/PycharmProjects/netmanchris_homekit/venv/lib/python3.7/site-packages/homekit-0.13.0-py3.7.egg/homekit/pair.py", line 78, in <module>
  File "/Users/christopheryoung/PycharmProjects/netmanchris_homekit/venv/lib/python3.7/site-packages/homekit-0.13.0-py3.7.egg/homekit/controller/controller.py", line 387, in finish_pairing
    pairing = perform_pair_setup_part2(pin, str(uuid.uuid4()), write_fun, salt, pub_key)
  File "/Users/christopheryoung/PycharmProjects/netmanchris_homekit/venv/lib/python3.7/site-packages/homekit-0.13.0-py3.7.egg/homekit/protocol/__init__.py", line 176, in perform_pair_setup_part2
    error_handler(response_tlv[1][1], 'step 5')
  File "/Users/christopheryoung/PycharmProjects/netmanchris_homekit/venv/lib/python3.7/site-packages/homekit-0.13.0-py3.7.egg/homekit/protocol/__init__.py", line 45, in error_handler
    raise AuthenticationError(stage)
homekit.exceptions.AuthenticationError: step 5
```

Here's the output.


``2019-07-05 17:49:54,039 __init__.py:0106 DEBUG #1 ios -> accessory: send SRP start request
2019-07-05 17:49:54,039 tlv.py:0134 DEBUG sending [
  6: (1 bytes) 0x01
  0: (1 bytes) 0x01
]

2019-07-05 17:49:54,040 tlv.py:0117 DEBUG receiving [
  6: (1 bytes) 0x01
  0: (1 bytes) 0x01
]

2019-07-05 17:49:54,040 __init__.py:0060 DEBUG write message: [
  6: (1 bytes) 0x01
  0: (1 bytes) 0x01
]

2019-07-05 17:50:01,868 tlv.py:0117 DEBUG receiving [
  6: (1 bytes) 0x02
  3: (384 bytes) 0x3fd55798df82689dcb173235a63158e25967cbdb6e2df1db80431327f629e4110679545eca5d9cd9231a6fe198909d4f410fa4e3526a3a54306d37ab0dbcf3f97015a7af175c1d8c0fc176d914bea3bae5db27c301c5e2c65f839d869191940862b7aca6370bf477bbdf64afde715775ca73ae1fc7c013ef479088fe47481393ae27703b6482df3d4079b8cd7f98a9294c19bb141a80d4546c2e87ce81baa0b9c675e5067cba53b53347520e58a7f2a32f340d275fa794cbcb1189a535c309cd2288e54a1ae2baa090d22a87222710f7dd646f5311eb242082c857a44467a4439e8203555d59368ddf0089cb7c92b5577fd3e80fa7d1ff2dc6834838b31908909393cf1fe4a86a55d0b66f22cb21726e1030fced9351bd2662b5f6ba3cbed8cd214cdfd47cd551155f718a5ea80421022ce52fe7ce17b61b63f7a1f86371a9b4e38f543197d3dad597b2312acc74faae0f044753b829b29be90591a52674b62179f3ccad5b1d8bdad6b28a43c0738d764ce7de3e15a3691d759b1927bfff81a4
  2: (16 bytes) 0x00000000000000000000000000000000
]

2019-07-05 17:50:01,868 __init__.py:0067 DEBUG response: [
  6: (1 bytes) 0x02
  3: (384 bytes) 0x3fd55798df82689dcb173235a63158e25967cbdb6e2df1db80431327f629e4110679545eca5d9cd9231a6fe198909d4f410fa4e3526a3a54306d37ab0dbcf3f97015a7af175c1d8c0fc176d914bea3bae5db27c301c5e2c65f839d869191940862b7aca6370bf477bbdf64afde715775ca73ae1fc7c013ef479088fe47481393ae27703b6482df3d4079b8cd7f98a9294c19bb141a80d4546c2e87ce81baa0b9c675e5067cba53b53347520e58a7f2a32f340d275fa794cbcb1189a535c309cd2288e54a1ae2baa090d22a87222710f7dd646f5311eb242082c857a44467a4439e8203555d59368ddf0089cb7c92b5577fd3e80fa7d1ff2dc6834838b31908909393cf1fe4a86a55d0b66f22cb21726e1030fced9351bd2662b5f6ba3cbed8cd214cdfd47cd551155f718a5ea80421022ce52fe7ce17b61b63f7a1f86371a9b4e38f543197d3dad597b2312acc74faae0f044753b829b29be90591a52674b62179f3ccad5b1d8bdad6b28a43c0738d764ce7de3e15a3691d759b1927bfff81a4
  2: (16 bytes) 0x00000000000000000000000000000000
]

2019-07-05 17:50:01,868 __init__.py:0118 DEBUG #3 ios -> accessory: send SRP verify request
2019-07-05 17:50:01,928 tlv.py:0134 DEBUG sending [
  6: (1 bytes) 0x03
  3: (384 bytes) 0xbd80a15615d7b174be703ddf82b9e6255c7acf1fc46387e4e28f96445323fda72bbdd40f98d95b0498517d109c17b698ae5d28cbf6d8bdea6fc0f960dd94b0ca5b91ca3cf1de2a9ae17ca044b459428d0652a33194dfcd5cf0c06f8dfa5504a011dfa68fd190aaf809873c80603b331b8023874a46c3c850f585dd584b8a1b3aaaa9fb232e7bd89a13a35d70b8c2758ff5ba74646c19796c400dfec0fb38fa86177244479ecb316e52e1181233c6061236c77afde0a3529899d7bbfc0d3a616faa535b218588477e0c3cfa4bb08c9021b751daf48480e2d90c011c552754d6a22411c12a337b3ff1e07ff3c9dbb09aa7d55493ba8b958d4f6f0442e91d275c6279c1d28e98ed4c30cdcbb96ddbdc8a7f82586a8f090b374bcc456a8877279ac847babf7f0a2c936d6e2c7a0600ce34a0041a5b539c78991d3f29fb5082ad5dc3eec79eae37e7a66e88cc3b5eeb87c2301890981f87bdf1f1786123a4226c4dd9050833df81bf17c62a6dc13caf0afa0bde5507e4dc6952b018e47be511eb0bd8
  4: (64 bytes) 0xfc5e032f34c4e107dee5fd6aa3f4929bcb3146ddc307eb0cd8e72577fd380c7426a0d3ff2550bd5052c266336d38f9880238a67cdd047695db970f5f52747ace
]

2019-07-05 17:50:01,928 tlv.py:0117 DEBUG receiving [
  6: (1 bytes) 0x03
  3: (384 bytes) 0xbd80a15615d7b174be703ddf82b9e6255c7acf1fc46387e4e28f96445323fda72bbdd40f98d95b0498517d109c17b698ae5d28cbf6d8bdea6fc0f960dd94b0ca5b91ca3cf1de2a9ae17ca044b459428d0652a33194dfcd5cf0c06f8dfa5504a011dfa68fd190aaf809873c80603b331b8023874a46c3c850f585dd584b8a1b3aaaa9fb232e7bd89a13a35d70b8c2758ff5ba74646c19796c400dfec0fb38fa86177244479ecb316e52e1181233c6061236c77afde0a3529899d7bbfc0d3a616faa535b218588477e0c3cfa4bb08c9021b751daf48480e2d90c011c552754d6a22411c12a337b3ff1e07ff3c9dbb09aa7d55493ba8b958d4f6f0442e91d275c6279c1d28e98ed4c30cdcbb96ddbdc8a7f82586a8f090b374bcc456a8877279ac847babf7f0a2c936d6e2c7a0600ce34a0041a5b539c78991d3f29fb5082ad5dc3eec79eae37e7a66e88cc3b5eeb87c2301890981f87bdf1f1786123a4226c4dd9050833df81bf17c62a6dc13caf0afa0bde5507e4dc6952b018e47be511eb0bd8
  4: (64 bytes) 0xfc5e032f34c4e107dee5fd6aa3f4929bcb3146ddc307eb0cd8e72577fd380c7426a0d3ff2550bd5052c266336d38f9880238a67cdd047695db970f5f52747ace
]

2019-07-05 17:50:01,928 __init__.py:0060 DEBUG write message: [
  6: (1 bytes) 0x03
  3: (384 bytes) 0xbd80a15615d7b174be703ddf82b9e6255c7acf1fc46387e4e28f96445323fda72bbdd40f98d95b0498517d109c17b698ae5d28cbf6d8bdea6fc0f960dd94b0ca5b91ca3cf1de2a9ae17ca044b459428d0652a33194dfcd5cf0c06f8dfa5504a011dfa68fd190aaf809873c80603b331b8023874a46c3c850f585dd584b8a1b3aaaa9fb232e7bd89a13a35d70b8c2758ff5ba74646c19796c400dfec0fb38fa86177244479ecb316e52e1181233c6061236c77afde0a3529899d7bbfc0d3a616faa535b218588477e0c3cfa4bb08c9021b751daf48480e2d90c011c552754d6a22411c12a337b3ff1e07ff3c9dbb09aa7d55493ba8b958d4f6f0442e91d275c6279c1d28e98ed4c30cdcbb96ddbdc8a7f82586a8f090b374bcc456a8877279ac847babf7f0a2c936d6e2c7a0600ce34a0041a5b539c78991d3f29fb5082ad5dc3eec79eae37e7a66e88cc3b5eeb87c2301890981f87bdf1f1786123a4226c4dd9050833df81bf17c62a6dc13caf0afa0bde5507e4dc6952b018e47be511eb0bd8
  4: (64 bytes) 0xfc5e032f34c4e107dee5fd6aa3f4929bcb3146ddc307eb0cd8e72577fd380c7426a0d3ff2550bd5052c266336d38f9880238a67cdd047695db970f5f52747ace
]

2019-07-05 17:50:04,767 tlv.py:0117 DEBUG receiving [
  6: (1 bytes) 0x04
  7: (1 bytes) 0x02
]

2019-07-05 17:50:04,767 __init__.py:0067 DEBUG response: [
  6: (1 bytes) 0x04
  7: (1 bytes) 0x02
]

2019-07-05 17:50:04,768 __init__.py:0169 DEBUG #5 ios -> accessory: send SRP exchange request
step 5
2019-07-05 17:50:04,768 pair.py:0085 DEBUG step 5
Traceback (most recent call last):
  File "/Users/christopheryoung/PycharmProjects/netmanchris_homekit/venv/lib/python3.7/site-packages/homekit-0.13.0-py3.7.egg/homekit/pair.py", line 78, in <module>
  File "/Users/christopheryoung/PycharmProjects/netmanchris_homekit/venv/lib/python3.7/site-packages/homekit-0.13.0-py3.7.egg/homekit/controller/controller.py", line 387, in finish_pairing
    pairing = perform_pair_setup_part2(pin, str(uuid.uuid4()), write_fun, salt, pub_key)
  File "/Users/christopheryoung/PycharmProjects/netmanchris_homekit/venv/lib/python3.7/site-packages/homekit-0.13.0-py3.7.egg/homekit/protocol/__init__.py", line 176, in perform_pair_setup_part2
    error_handler(response_tlv[1][1], 'step 5')
  File "/Users/christopheryoung/PycharmProjects/netmanchris_homekit/venv/lib/python3.7/site-packages/homekit-0.13.0-py3.7.egg/homekit/protocol/__init__.py", line 45, in error_handler
    raise AuthenticationError(stage)
homekit.exceptions.AuthenticationError: step 5``

**Comment by jlusiardi** [comment]
same here, try to use 0.14.0 please

**Comment by jlusiardi** [comment]
I think we can close this because of inactivity.
