### ISSUE TITLE
Support Koogeek light strip?

### ISSUE THREAD

**Issue by moinahmed001** [jlusiardi/homekit_python#168]
Does this script support Koogeek light strip?

**Comment by Jc2k** [comment]
I've seen the Koogeek LS1 work for a few users in home-assistant (which uses the homekit_python library). But if you are asking because you want to buy one, we can't guarantee you'll not get hardware from a different batch or with a different firmware version that works differently.

**Comment by jlusiardi** [comment]
Hello @moinahmed001,

as @jc2k wrote, we cannot give any guarantee. But there are two other accessories from Koogeek in our tested devices section so i would say, chances might not be that bad. If you decide to give the  LS1 and homekit_python a chance, let us know the results! Would be happy to have it listed under https://github.com/jlusiardi/homekit_python/tree/master/doc/tested_devices

**Comment by jlusiardi** [comment]
I think we can close this because of inactivity.
