### ISSUE TITLE
set_hue_get_callback not defined

### ISSUE THREAD

**Issue by chrisburns007** [jlusiardi/homekit_python#172]
Line 46 of hue.py states set_brightness_get_callback instead of set_hue_get_callback... this appears to be a typo but result is set_hue_get_callback is not defined.

    def set_hue_set_callback(self, callback):
        self._hueCharacteristic.set_set_value_callback(callback)

    def set_**brightness**_get_callback(self, callback):
        self._hueCharacteristic.set_get_value_callback(callback)

**Comment by jlusiardi** [comment]
Thanks! Fixed that :)
