### ISSUE TITLE
Feature request: Add support for Abode home security system

### ISSUE THREAD

**Issue by Tediore** [jlusiardi/homekit_python#173]
Abode has recently released HomeKit support for all of its security gateways (gen 1, gen 2, and Iota). Gen 1 and 2 HomeKit support is currently in beta, but I have access to it for my gen 1 gateway. 

Home Assistant recognizes the Abode gateway as a HomeKit device, but pairing with HomeKit Controller ultimately fails even when using the correct HomeKit code. It says "pairing failed as the device can no longer be found" or something similar.

I can provide any specific error messages related to the failed pairing or try to find the JSON for the device if needed.

Edit: To clarify, I see that HomeKit Controller already supports `alarm_control_panel`, so I'm guessing it's maybe something specific with Abode that is creating an issue. I am, however, able to successfully pair the device to an actual HomeKit hub (I borrowed an iPad to use as a HomeKit hub because I own no Apple devices).

**Comment by Jc2k** [comment]
@Tediore Are you able to pair using the homekit_python CLI tools? @jlusiardi isn't a HA user so won't be able to help if you can't reproduce the problem with the CLI tools.

If you can pair with it with the homekit_python CLI then it will be a HA ticket and we'll need to take it over there...

**Comment by Tediore** [comment]
Ah whoops. 🤦‍♂ Thanks, I'll try with the CLI.

**Comment by Tediore** [comment]
I am indeed unable to pair using the CLI. I receive the following error:
`Remote end closed connection without response`

It then no longer shows up in the list of devices when I run `homekit.discover` until I disconnect the gateway from the network by unplugging the Ethernet cable or if after what seems like a random period of time if I leave the gateway alone.

Here's the output for it from `homekit.discover`:
```
Name: HPGW-B0C5CA326573._hap._tcp.local.
Url: http_impl://10.0.0.45:46286
Configuration number (c#): 1
Feature Flags (ff): No support for HAP Pairing (Flag: 2)
Device ID (id): [redacted]
Model Name (md): Bridge
Protocol Version (pv): 1.1
State Number (s#): 1
Status Flags (sf): Accessory has not been paired with any controllers. (Flag: 1)
Category Identifier (ci): Bridge (Id: 2)
```
I'm guessing that feature flag is relevant here?

**Comment by jlusiardi** [comment]
Glad to see people using more accessories with this software. Or at least try to ;)

> The Home app also warns that the device isn't HomeKit certified. Might also be relevant.
Yes kind of, this warning means AFAIK that Abode is not using a hardware chip to handle the HomeKit Crypto (but not 100% sure though). The feature flag is hitting the same spot. Nevertheless this should not be bad.

I have a few questions to further help you:
- can you tell me which version of the HomeKit_python module you are using?
- can you reset the Abode gateway to factory settings (at least the HomeKit part) just to be sure to have a clean standing?
- please rerun the pair command with `--log DEBUG` and give me the output. This might contain more hints

**Comment by Tediore** [comment]
- I just `pip install`ed the tool yesterday, but then I ran this to fix an issue with a `KeyError` I was getting:
```
pip3 install --user -e git+https://github.com/jlusiardi/homekit_python.git@fix_158_unknown_categories#egg=homekit
```
- There doesn't appear to be a way to reset the HomeKit part, but I can certainly reach out to Abode support about this if you think it'd be important.
- I will do this tonight. Wanted to at least answer the other questions now as it appears we are in much different time zones (US Central time here).

**Comment by Tediore** [comment]
Alright, here's the log output: https://paste.ubuntu.com/p/px78Wx24b4/

**Comment by chrismccracken** [comment]
+1

**Comment by Tediore** [comment]
I'm trying to find someone with the Abode Iota system who would be willing to try pairing with the CLI to see if this issue is simply because HomeKit support for the gen 1 and gen 2 gateways is still in beta. Hopefully I can have some information regarding that soon.

**Comment by jlusiardi** [comment]
@Tediore looks like a pretty standard config to me. I can only guess. 

Did you double check the pin? 

Is the pin static or regenerated on each pairing attempt?

> because HomeKit support for the gen 1 and gen 2 gateways is still in beta

That also might be a suspect ;)

**Comment by Tediore** [comment]
Yes, I made sure to double-check the PIN. The PIN appears to be static.

I figured it being beta would be a likely cause, but I wanted to check with you anyway. 😉 That's also why I'm looking for someone with an Iota system that would be willing to help out.

Thanks for the help so far!

**Comment by Jc2k** [comment]
It would be good to get a pcap of a successful pairing with an iOS device. A wire shark dump of promiscuous WiFi monitoring on tcp ip connections between an iPhone/iPad and the gateway. Because if you can pair with iOS then it probably is on our side that needs fixing.

https://wiki.wireshark.org/CaptureSetup/WLAN

**Comment by Tediore** [comment]
I can definitely try that. I'll read up on and install WireShark and give it a try this week.

**Comment by Tediore** [comment]
Alright, I have the output for all packets sent to/from the gateway. The gateway is 10.0.0.45 and the iPad is 10.0.0.54 (oddly enough)
[output.zip](https://github.com/jlusiardi/homekit_python/files/3942863/output.zip)

**Comment by Tediore** [comment]
System appears to work properly. Thanks!
