### ISSUE TITLE
Is there a way to generate the -f ${PAIRINGDATAFILE} for existing devices?

### ISSUE THREAD

**Issue by earlthesquirrel** [jlusiardi/homekit_python#179]
I'd like to remove a device and was trying to figure out the PAIRINGDATAFILE.
Since the device was added using a different mechanism, I don't have a file to start with.

I'm trying to reset a device that hasn't unpaired correctly... which this package would be great for.

**Comment by Jc2k** [comment]
Can you give some more context about whats happened?

In general the answer is no - the pairing data file contains the results of a cryptographic exchange and includes the only copy of the only private key the accessory trusts.

**Comment by earlthesquirrel** [comment]
I have a device (a motion sensor) installed based on a Particle.
The device doesn't show up in the negative home app (I deleted from there) but using  python3 -m homekit.discover it shows up as paired.  (I have a couple devices that have gotten into this state... the Particle has been what I've been using to test with, to try to figure out what's not happening properly when the device is removed from the native Home app.

**Comment by jlusiardi** [comment]
Hi @earlthesquirrel,

each HomeKit accessory has its more or less unique way to reset it (and by that remove all pairings). E.g. I have OSRAM SMART+ Classic E27 Multicolor (BLE)  which must be turned on and of with a special pattern. Look into the manual for the device.  HTH.

Joachim

**Comment by earlthesquirrel** [comment]
Well one product my company produces (so the manual is what we write :-) )
So, trying to figure out if something is left over in the Homekit DB, etc.  
This particle based motion sensor is something that I've been able to get into the same state... which made it useful for debugging.. the question is now how to clear this info..

**Comment by jlusiardi** [comment]
I do not exactly know this `particle` or the software you are running on it but there should be some kind of storare in flash/eeprom?

**Comment by earlthesquirrel** [comment]
It's a Particle photon (see : https://store.particle.io/?utm_term=&utm_campaign=Dynamic+Search+Ads+-+S8&utm_source=adwords&utm_medium=ppc&hsa_grp=67675299738&hsa_acc=5060272854&hsa_tgt=dsa-835611334005&hsa_kw=&hsa_src=g&hsa_mt=b&hsa_cam=1697512981&hsa_ver=3&hsa_ad=329939807759&hsa_net=adwords&gclid=EAIaIQobChMItO_pq-if6AIVAuiGCh3xQQrhEAAYASAAEgLjivD_BwE)    The SW I've based this off of is : https://github.com/ljezny/Particle-HAP.

**Comment by earlthesquirrel** [comment]
I could try changing the pairing code in my code... not sure if that would do it...
Just wanted to make sure no left over data was orphaned...

**Comment by jlusiardi** [comment]
https://github.com/ljezny/Particle-HAP/blob/master/src/HKPersistor.cpp#L19 suggests it is stored in some kind of eeprom. Perhaps https://community.particle.io/t/how-to-do-a-factory-reset/2579 might help, but you need to reinstall the homekit code again.

**Comment by jlusiardi** [comment]
Hello @earlthesquirrel 
is there anything more we can do here?

**Comment by jlusiardi** [comment]
I do not think we can do much here
