### ISSUE TITLE
iHome SP5 Tips

### ISSUE THREAD

**Issue by sberryman** [jlusiardi/homekit_python#18]
It took me close to an hour to figure out how to pair an iHome SP5 switch, may be worth adding to the readme.

Steps:
1. Reset the device by holding the power switch for 12 seconds
1. Open the iHome app and tap the `Add Device` button
1. Select a switch and tap `Continue`
1. Allow access to your home network
1. Watch the switch closely as the blinking white indicator light switches to solid, quickly exit the app when the light transitions

If you don't exit the app quickly enough and the setup screen on your mobile device transitions to the camera/homekit code input screen, you waited too long and need to start over. I was not able to pair the device successfully until I managed to exit the app before the homekit code input screen.

**Comment by jlusiardi** [comment]
Ah, i guess this is because the iHome SP5 gets information over blue tooth on how to join your wifi. This is nothing i targeted, because this should be device specific.

Perhaps this is worth adding to the readme.

**Comment by sberryman** [comment]
Yes, not sure how the iPhone was communicating with the switch to transmit WiFi details but most likely as you described, using bluetooth.

Not sure why it would fail with an authentication error on pairing if you let it get to the homekit code input screen though.

**Comment by sberryman** [comment]
Yes, I have to exit the iHome app before the scanning screen appears otherwise it would always fail at step 5 (authentication). That is without me doing anything in the iHome app other than the camera activating and it ready to scan a code.

**Comment by jlusiardi** [comment]
As I do not exactly know this device, can you try to pair it with your iPhone first, then unpair? By that it should be in the wifi and free to pair again. 

"Not sure why it would fail with an authentication error on pairing if you let it get to the homekit code input screen though." Did you enter the code here? Because if so, there already is one pairing and a new (2nd) pairing could not be done without using the function Add Pairing (as described in chapter 4.11)

**Comment by sberryman** [comment]
I think we can close this issue, @brianhanifin reported on a different issue that iHome was having cloud problems yesterday.

![image](https://user-images.githubusercontent.com/324437/39475611-be3dd274-4d0d-11e8-88fe-f25558ddeb30.png)
