### ISSUE TITLE
remove_pairings over IP uses wrong Content-Type header

### ISSUE THREAD

**Issue by An00bIS47** [jlusiardi/homekit_python#188]
Hi,

when removing pairings over IP, a wrong Content-Type header is used. It seems to use application/hap+json.

```
POST /pairings HTTP/1.1
Host: ...
Content-Type: application/hap+json
Content-Length: 44

=== [bodyData] (len:44) ===
06 01 01 00 01 04 ...
======
```
The HomeKit documentation state the following on page 48
> The MIME type for requests and responses is application/pairing+tlv8.

**Comment by jlusiardi** [comment]
should be fixed with #191, just waiting for the tests

**Comment by An00bIS47** [comment]
Wow. That was fast :) Thanks for that

I can verify, that the changes worked.
```
POST /pairings HTTP/1.1
Host: ...
Content-Type: application/pairing+tlv8
Content-Length: 44


=== [bodyData] (len:44) ===
06 01 01 00 01 04 ... 
```

**Comment by jlusiardi** [comment]
Cool thanks for your report & confirmation!
