### ISSUE TITLE
homekit.get_accessories.py Error

### ISSUE THREAD

**Issue by raufis27** [jlusiardi/homekit_python#19]
/usr/bin/python3: Error while finding spec for 'homekit.get_accessories.py' (AttributeError: module 'homekit.get_accessories' has no attribute '__path__')

Any ideas ?

**Comment by jlusiardi** [comment]
seems to be the extra .py in the readme.

Does this help?

**Comment by raufis27** [comment]
Yes it does. Thank you. I have another question. For some reason it takes about 10 seconds to put_characteristic. Is there any way to make it faster ? Thank you.

**Comment by jlusiardi** [comment]
You are right, 10s seems slow. Should be optimized, but honestly, never looked into profiling python before. Can you please open a new issue for that and close this one since it was answered? Thanks.

**Comment by andreyxc** [comment]
Tell me what to do with extra .py ?

**Comment by andreyxc** [comment]
python3 demoserver.py

2022-09-04 19:37:28,763 demoserver.py:0048 INFO starting
Traceback (most recent call last):
  File "/home/pi/homekit_python-master/demoserver.py", line 62, in <module>
    httpd.publish_device()
  File "/home/pi/homekit_python-master/homekit/accessoryserver.py", line 1347, in publish_device
    self.zeroconf.check_service(self.zeroconf_info, allow_name_change=False)
AttributeError: 'Zeroconf' object has no attribute 'check_service'
