### ISSUE TITLE
list_pairings don't add seperators to a list of pairings

### ISSUE THREAD

**Issue by An00bIS47** [jlusiardi/homekit_python#193]
Hi,

I have encountered another bug.

The list_pairings command should return a TLV8 list of already established pairings as you have implemented. But the items should be separated by a zero-length based separator (0XFF)  
Have a look at page 46 of the Documentation.

The controller part can not handle such a separator and fails to handle the response if the response contains a separator. Without separator, it works fine.

I haven’t tested your accessory server myself, but by looking at the code I can tell, that there is no separator added to the response TLV8.

Another question a bit off-topic:
With version 0.15.0 the controller closed a connection, even if the keep-alive header was set by an accessory server. With the current git version, the controller keeps the connection open, if the header is set and waits until the connection is closed by the server. Is this behavior intended? 

Thank you!

**Comment by jlusiardi** [comment]
Hi,

> But the items should be separated by a zero-length based separator (0XFF). Have a look at page 46 of the Documentation.

You are right. I can add a separator entry here even if it is not strictly necessary (because the types of the entries differ).  This is in https://github.com/jlusiardi/homekit_python/blob/d1b22be0711d0f45f12d3391addfda16e73a299d/homekit/accessoryserver.py#L893 and following.

> The controller part can not handle such a separator and fails to handle the response if the response contains a separator. Without separator, it works fine.

What is the exact problem here? Are you communicating via IP 
https://github.com/jlusiardi/homekit_python/blob/d1b22be0711d0f45f12d3391addfda16e73a299d/homekit/controller/ip_implementation.py#L116 
or BLE 
https://github.com/jlusiardi/homekit_python/blob/d1b22be0711d0f45f12d3391addfda16e73a299d/homekit/controller/ble_impl/__init__.py#L86)

Regarding the the keep-alive, i did not take this into consideration yet.

**Comment by An00bIS47** [comment]
I am communicating over IP. Sorry, I forgot to mention this in the first post!

The output when calling the homekit.list_pairings command via IP
is for example when there are more than 1 entry in the pairings list.
```
Not enough data left. 18 vs 82
```

I am not sure, if I am doing something wrong with constructing a separator entry but this is the output I get when using 0xFF as type and 0 as length as the seperator entry. But I have to check if these values are correct.

**Comment by jlusiardi** [comment]
> I am communicating over IP. Sorry, I forgot to mention this in the first post!
No problem. I will definitely will have a look at the issue!

**Comment by jlusiardi** [comment]
Could you try with the new commit and show me an example byte stream that breakst the `list_pairings` command? I could not reconstruct the bug here.

**Comment by An00bIS47** [comment]
Hi @jlusiardi 
> I could not reconstruct the bug here.
That's because the bug was on my side. Sorry for the confusion in this regard! It was indeed a  implementation of the separator entry on my side.

**Comment by jlusiardi** [comment]
ok no problem, but does the branch conform more to the spec as before (in your humble opinion)?

Also, you are welcome to share knowledge and questions about homekit implementation :+1:

**Comment by An00bIS47** [comment]
> ok no problem, but does the branch conform more to the spec as before (in your humble opinion)?
I would say of course it's more conform to the spec now :) But I don't know if this was changed with R2 of the spec.

I appreciate the offer and I am glad share my experience with HomeKit :) I am writing my own implementation for an ESP32 controller and I am using the controller part from you to test my server. 

I still have to implement the timed-based reading/writing (?) of characteristics and I have to see what else was added to the R2 spec but the basic stuff is working for IP communication. BLE is currently out-of-scope until I have implemented everything I plan to. But thanks to you I have another reference implementation :)

I don't know if you know, but Apple released a reference implementation here which supports both BLE and IP: https://github.com/apple/HomeKitADK

**Comment by jlusiardi** [comment]
> I am using the controller part from you to test my server.

So you are doing this without any iOS device as a reference?

> I still have to implement the timed-based reading/writing (?) of characteristics and I have to see what else was added to the R2 spec but the basic stuff is working for IP communication. 

I have not investigated this field since none of my accessories uses this. But perhaps we I should ;)

**Comment by An00bIS47** [comment]
> So you are doing this without any iOS device as a reference?

No, I use also an iOS device as a reference, but this is a bit tricky, because you don't see the exact error causing a problem. And it is difficult for an automated testing :)

Btw.: Regarding the "keep-alive" problem. This is also not a bug on your side. I have accidentally removed a CRLF from the HTTP response and this caused the trouble. Again sorry for the confusion. Sometimes a little bit more sleep helps :)

**Comment by jlusiardi** [comment]
> Btw.: Regarding the "keep-alive" problem. This is also not a bug on your side.

No problem, I also know that more-sleep-issue ;)

**Comment by jlusiardi** [comment]
I'll close this one for now. Please feel welcome to open a new one for additional questions.
