### ISSUE TITLE
Osram A60 C pairing fails with "Not enough data left. 105 vs 143"

### ISSUE THREAD

**Issue by antrov** [jlusiardi/homekit_python#194]
Hi,

First of all, thank you for your work and the great bunch of code.

During pairing with Osram A60 C, I encountered following error: `Not enough data left. 105 vs 143` where both numbers differs on each run.

device manufacturer : LEDVANCE
device model : Ledvance A60 C
device firmware version : **01.1.41**
version of homekit library: **0.17.0**

Steps according to https://github.com/jlusiardi/homekit_python/blob/master/doc/tested_devices/OSRAM%20A60%20Ce.md

### Step 1 - discovery
```
Name: LEDVANCE A60 C
MAC: e4:b8:74:65:b7:2b
Configuration number (cn): 0
Device ID (id): 96:D8:6D:C2:35:CA
Compatible Version (cv): 2
Global State Number (s#): 1
Status Flags (sf): The accessory has not been paired with any controllers. (Flag: 1)
Category Identifier (ci): Lightbulb (Id: 5)
```

### Step 2 & 3
Success

### Step 4 - pairing
few runs
```
Not enough data left. 125 vs 235
Not enough data left. 82 vs 128
Not enough data left. 22 vs 254
Not enough data left. 61 vs 178
Not enough data left. 87 vs 207
Not enough data left. 82 vs 224
Not enough data left. 53 vs 167
Not enough data left. 161 vs 204
Not enough data left. 69 vs 250
Not enough data left. 69 vs 236
Not enough data left. 54 vs 160
Not enough data left. 17 vs 179
Not enough data left. 74 vs 104
Not enough data left. 9 vs 234
Unable to resolve device services + characteristics (?)
```

Testing process with DEBUG flag shows that pairing fails on different stages of reading characteristics.

EDIT: Attached log [homekit_debug.log](https://github.com/jlusiardi/homekit_python/files/4604035/homekit_debug.log)

**Comment by jlusiardi** [comment]
Hi, 

since you already did a run with DEBUG flag, would you mind sharing those fails so we could analyze the exact position in code? Thanks!

Regards
Joachim

**Comment by antrov** [comment]
Sure. Attached to my previous post.

**Comment by jlusiardi** [comment]
Ok I can confirm the issue with mine es well. Will dig back to see what caused this.

**Comment by jlusiardi** [comment]
seems it was introduced with 6450b5506a1d9219fbe4adf412b02134a2d4767e

Will need to have a deeper look...

**Comment by jlusiardi** [comment]
It is a bug in my lib: https://github.com/jlusiardi/tlv8_python/issues/13

**Comment by jlusiardi** [comment]
Can you try the current master please?

**Comment by antrov** [comment]
Works perfectly 👌

Loosely related question: is it normal that writing to char takes ~10s?

**Comment by jlusiardi** [comment]
I never payed much attention, but it takes about 8s here... 
Open an issue, if this is to bad, but I cant promise anything
