### ISSUE TITLE
Can someone give out an example of writing Charististic with value based on TLV8 format? thank you.

### ISSUE THREAD

**Issue by belkinhappyzj** [jlusiardi/homekit_python#198]
Can someone give out an example of writing Charististic with value based on TLV8 format? thank you.
e.g.  with CMD :
python3 -m homekit.put_characteristic -f ${PAIRINGDATAFILE} -a ${ALIAS} -c ${Characteristics} ${value} \[--adapter ${ADAPTER}] [--log ${LOGLEVEL}]

Thank you.

**Comment by jlusiardi** [comment]
It could be done with the `homekit.put_characteristic ` but it is not simple. You have to construct a TLV8 structure, encode it to bytes and encode those bytes using base64.

Perhaps you can have a look at https://github.com/jlusiardi/homekit_python/blob/camera_client/homekit/get_camera_stream.py and the other code from the camera_client branch. I need to write TLV8 code stuff to some characteristics there.

**Comment by belkinhappyzj** [comment]
thanks a lot!

**Comment by jlusiardi** [comment]
Feel free to reopen ;)
