### ISSUE TITLE
KeyError: 'format'

### ISSUE THREAD

**Issue by nickpl456** [jlusiardi/homekit_python#20]
When I try to run 
`python3 -m homekit.put_characteristic -f "/home/pi/test" -c "1.10" -v "1"`
I'm getting the error:

    Traceback (most recent call last):
      File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/root/.local/lib/python3.5/site-packages/homekit/put_characteristic.py", line 73, in <module>
        format = data['characteristics'][0]['format']
    KeyError: 'format'

If I comment out
`format = data['characteristics'][0]['format']`
from put_characteristic.py then I'm able to run the command successfully.

**Comment by jlusiardi** [comment]
Hi,

can you post the output of the get accessoires?
```
python3 -m homekit.get_accessories -f "/home/pi/test"  -o json
```
Also what device do you connect to?

Considering Table 5-3 (page 65) of the spec, the format field is required. You are right, unless it is boolean, it does not matter.

**Comment by nickpl456** [comment]
Connecting to the Leviton DH6HD.

Here's the output:
[get_accessories.txt](https://github.com/jlusiardi/homekit_python/files/1964192/get_accessories.txt)

(I'm getting the feeling these devices don't follow Apple's spec nearly as well as they should)

**Comment by jlusiardi** [comment]
Ok, I just dug a little deeper: What does the following command return?

```
python3 -m homekit.get_characteristic -f "/home/pi/test"  -c "1.10" -m
```

I suspect something like this json to be returned:
```
{
    "characteristics": [
        {
            "iid": 10,
            "value": false,
            "aid": 1,
            "format": "int"
        }
    ]
}
```

I guess the format is missing (but should be there as the meta parameter includes format (Table 5-14 on page 84ff). So you might be right, that those devices could be closer to the spec.

I will think for a work around.

**Comment by nickpl456** [comment]
Yep, exactly what you suspected, it's missing the format:

    {
        "characteristics": [
            {
                "value": 0,
                "iid": 10,
                "aid": 1
            }
        ]
    }

**Comment by jlusiardi** [comment]
I guess this will need some more thinking. Just skipping the line you mentioned in the original post will break sending boolean values (at least to the device I have). I will try to fix this in [a bew branch](/jlusiardi/homekit_python/tree/fix_20_missing_types).

**Comment by jlusiardi** [comment]
can you try to checkout the new branch I mentioned above? I now read the accessories data (in your case with format) into the file with the pairing data. This should fix it.

**Comment by nickpl456** [comment]
That fixed the error. The only strange thing I'm noticing is that the command 

    python3 -m homekit.put_characteristic -f "/home/pi/test" -c "1.10" -v "1" 

does not work. I had to add '1' to the bool if statement to this before it would work:

    if value in (True, 'true', 1, '1'):

I might suggest instead of tying to list every way someone might write true do something like:

    from distutils.util import strtobool
    if strtobool(value) == True:

Like I said I'm definitely not a programmer so there might be a very good reason not to do this, and in that case I'd suggested just checking to see if the user entered a 0 or 1 and error out on anything else.

Thank you again!

**Comment by jlusiardi** [comment]
hey,

i do not see any point why not to use distutils.util.strtobool(), just did not know it existed.

Just committed with your proposal.

**Comment by nickpl456** [comment]
Awesome, thanks!
