### ISSUE TITLE
potential base64 encode issue on TLV8 data

### ISSUE THREAD

**Issue by belkinhappyzj** [jlusiardi/homekit_python#200]
The issue is observed with using encoded TLV8 data in command line e.g. 
python -m homekit.put_characteristic -f steven.json -a RT -c 1.58 "Af8BAQUC\\/wEBAQMBAwX......"
The base64 encloding used here is MIME(RFC2045) which "\\" is a legal letter, however the actual data sent out by controller is  Af8BAQUC\\\\/wEBAQMBAwX......  where it automatically insert an extra "\\" before "\\" which seems to be due to escape character?  this issue is making the PUT operation fail due to invalid data, would you please take a look and see if there could be a quick "patch" of "fix" available, thanks.

**Comment by jlusiardi** [comment]
Hi,

thanks for the report. I just tried to reproduce with `test.py`

```python
import sys

print(sys.argv)
```
and calling `python3 test.py "foo\/bar"` prints
```
['test.py', 'foo\\/bar']
```

**Comment by belkinhappyzj** [comment]
Hi jlusiardi, thanks for your investigation, I am running it via CMD CLI on windows OS, maybe this is 
a windows specific issue?  BTW, read it from a file is an great idea!, thanks.

**Comment by jlusiardi** [comment]
I made a new branch: `fix_200` and added the load content from file feature: `-c 1.9 @somefile`

Install with:
```
pip3 install --upgrade -e git+https://github.com/jlusiardi /homekit_python.git@fix_200#egg=homekit[IP]
```
