### ISSUE TITLE
problem with installing on macOs

### ISSUE THREAD

**Issue by ashrafyassin** [jlusiardi/homekit_python#203]
I'm having trouble installing the python package on my mac, having macOs Catalina.
im running this command on my terminal: "pip3 install --user homekit[IP]" 
and i get: "zsh: no matches found: homekit[IP]"
how should i probably install the package?

**Comment by Jc2k** [comment]
I think thats your shell trying to interpret `[` as a special character. Does putting brackets around it like this work?

```
pip3 install --user "homekit[IP]"
```

**Comment by ashrafyassin** [comment]
yup it worked, thanks.
escpabing the square brackets also works.
`pip3 install --user homekit\[IP\]`
