### ISSUE TITLE
ImportError: cannot import name 'HomeKitServer'

### ISSUE THREAD

**Issue by emanuelelaface** [jlusiardi/homekit_python#208]
I just installed the homekit on a Debian 10 following the instructions but when I import the module I have:

ImportError: cannot import name 'HomeKitServer' from 'homekit' (/home/ema/.local/lib/python3.7/site-packages/homekit/__init__.py)

The version installed of homekit is the 0.18.0 and the version of Python is Python 3.7.3.

**Comment by jlusiardi** [comment]
Hi,
just tried to reenact the problem and took a debian 10 docker container, installed `python3-pip` package and did `pip3 install homekit[IP]`. After that `import homekit` in a python3 shell works like a charm. 

Do you have a homekit direktory as well?
What is the layout of your code?

**Comment by Jc2k** [comment]
Did a `git grep HomeKitServer`. It's a typo in README.md. I don't know how we missed it all this time - I think I always just use demoserver.py.

**Comment by emanuelelaface** [comment]
I see. I used the demoserver.py and it runs correctly, so HomeKitServer does not exist in the library, you should fix the README.md.

**Comment by jlusiardi** [comment]
Just updated the readme
