### ISSUE TITLE
homekit.discover: 'adress': inet_ntoa(info.addresses[0]), list index out of range

### ISSUE THREAD

**Issue by tobikellner** [jlusiardi/homekit_python#216]
Hi all,

when trying to run homekit.discover I get the following Error:

```sh
tobias@tobias-VirtualBox:~$ python3 -m homekit.discover
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tobias/.local/lib/python3.8/site-packages/homekit/discover.py", line 51, in <module>
    results = Controller.discover(args.timeout)
  File "/home/tobias/.local/lib/python3.8/site-packages/homekit/controller/controller.py", line 92, in discover
    return discover_homekit_devices(max_seconds)
  File "/home/tobias/.local/lib/python3.8/site-packages/homekit/zeroconf_impl/__init__.py", line 96, in discover_homekit_devices
    'address': inet_ntoa(info.addresses[0]),
IndexError: list index out of range
```

It seems that there are no addresses discovered. However it's an uncatched Exception. 

Nethertheless I'm wondering what I'm doing wrong - do I have to reset my Homekit devices that are currently paired to a single IPad that is not acting as a Homekit Controller - in order to have them found? Network to the VM is bridged and my Velux Active Hub (native Homekit device) is pingable.

Thanks for your support

**Comment by jlusiardi** [comment]
Hi,

First of all, you should not need to reset anything. Also paired devices should be listed.

Can you send the IP if VM and the Velux Active Hub?

Can you also add a `print(info)` to `homekit/zeroconf_impl/__init__.py:92` and post the output? I just ran a discover in my home wifi (without any homekit devices) and saw no crash.

Greetings
Joachim

**Comment by tobikellner** [comment]
Hi 

thanks for your reply @jlusiardi. With the output I found that I was running a HomeBridge instance on the same machine that didn't got an IP-Address which caused the error. Uninstalling the homebridge (which was only for test purposes anyway) solved the error.

Now discover runs smooth. 
Thanks and greetings
Tobi

**Comment by jlusiardi** [comment]
You're welcome ;)
