### ISSUE TITLE
Support for RGBW lamp

### ISSUE THREAD

**Issue by nevoomer** [jlusiardi/homekit_python#217]
Any change I can use a RGBW lamp? (change color, brightness, etc)
thanks

**Comment by jlusiardi** [comment]
I use https://github.com/jlusiardi/homekit_python/blob/master/doc/tested_devices/OSRAM%20A60%20Ce.md so this should be possible. May depend on your device.

**Comment by nevoomer** [comment]
I figured it out, thanks!
