### ISSUE TITLE
TV Support

### ISSUE THREAD

**Issue by nevoomer** [jlusiardi/homekit_python#218]
I'm trying to add a not-really-smart TV device manually, but cannot get / change status of it in ios home app
cannot get status (stuck on updating) while using TV icon

defined a special class as:
```
class TVService(AbstractService, OnCharacteristicMixin):
    def __init__(self):
        AbstractService.__init__(self, '000000D8-0000-1000-8000-0026BB765291', homekit.model.get_id())
        OnCharacteristicMixin.__init__(self, homekit.model.get_id())
```

for now, only interested in showing tv status (on/off), so code is pretty simple:

```
class TVDevice(object):
    def __init__(self, device_name):
        self.device_name = device_name
        self.device_ip = tv_client_devices[self.device_name]['ip']
        self.device_listening_port = 9080

    def get_state(self):
        try:
            socket.create_connection((self.device_ip, self.device_listening_port), timeout=1)
            # if its offline, exception occurred
            power_state = 1
        except Exception:
            power_state = 0

        write_to_log(f"[{self.device_name}] Power state: {power_state}")
        return power_state

    def set_state(self, value):
        write_to_log(f"[{self.device_name}] Power state change request: {value}")
```

created an accessory, added a service of that class, defined get_callback and set_callback, which seems to work - but on home app it shows as "updating" and status isn't changing (can see on debug log that it returns 0 / 1 as it should)

```
def get_tv_accessory(accessory_name):
    accessory = homekit.model.Accessory(accessory_name, 'Home', 'HisenseTV', '0001', '0001')
    service = TVService()

    tv_object = tv.TVDevice(accessory_name)

    service.set_on_set_callback(tv_object.set_state)
    service.set_on_get_callback(tv_object.get_state)

    accessory.services.append(service)
    return accessory

def start_tv_device(device):
    try:
        httpd = AccessoryServer(os.path.expanduser(CONFIG_FILE))
        httpd.accessories.add_accessory(get_tv_accessory(device))
        write_to_log(f'[{device}] Setup is done. starting http service')
        httpd.publish_device()
        httpd.serve_forever()
    except KeyboardInterrupt:
        httpd.unpublish_device()
```

if im changing device type from uuid to switch for example (public.hap.service.switch), everything is working great but I can only choose icon of switch \ light \ fan in ios home app.

any ideas how to fix it?

thanks

**Comment by Jc2k** [comment]
You need to implement the TV Service as specified by apple. The TV service is much more complicated than a light bulb. you can't just turn a light bulb service into a TV service with no other changes. E.g. I don't think the `on` characteristic is part of the TV service.  You need to implement `active`. There are probably other's that are required by the spec, and if you don't add them all then iOS won't like your fake accessory. I don't think there is a public spec for what is required and what is allowed though.

This might give you some clues, its a mock TV implemented in javascript (reverse engineered):

https://github.com/homebridge/HAP-NodeJS/blob/master/src/accessories/TV_accessory.ts

**Comment by nevoomer** [comment]
I figured it out, whats needed is:

"""
class ActiveCharacteristic(AbstractCharacteristic):
    def __init__(self, iid):
        AbstractCharacteristic.__init__(self, iid, CharacteristicsTypes.ACTIVE, CharacteristicFormats.uint8)
        self.valid_values = {
          0: "Inactive",
          1: "Active"
        }
        self.name = "Active"
        self.description = "Active"
        self.format = "uint8"
        self.perms = ['pr', 'pw', 'ev']
        self.type = "000000B0-0000-1000-8000-0026BB765291"


class ActiveIdentifierCharacteristic(AbstractCharacteristic):
    def __init__(self, iid):
        AbstractCharacteristic.__init__(self, iid, CharacteristicsTypes.ACTIVE_IDENTIFIER, CharacteristicFormats.uint32)
        self.name = "ActiveIdentifier"
        self.description = "ActiveIdentifier"
        self.format = "uint32"
        self.perms = ['pr', 'pw', 'ev']
        self.type = "000000E7-0000-1000-8000-0026BB765291"
        self.minValue = 0


class TVService(AbstractService):
    def __init__(self, name, manufacturer, model, serialnumber, firmwarerevision):
        AbstractService.__init__(self, '000000D8-0000-1000-8000-0026BB765291', homekit.model.get_id())
        self.append_characteristic(ManufacturerCharacteristic(homekit.model.get_id(), manufacturer))
        self.append_characteristic(ModelCharacteristic(homekit.model.get_id(), model))
        self.append_characteristic(NameCharacteristic(homekit.model.get_id(), name))
        self.append_characteristic(SerialNumberCharacteristic(homekit.model.get_id(), serialnumber))
        self.append_characteristic(FirmwareRevisionCharacteristic(homekit.model.get_id(), firmwarerevision))
        self.append_characteristic(ActiveCharacteristic(homekit.model.get_id()))
        self.append_characteristic(ActiveIdentifierCharacteristic(homekit.model.get_id()))

    def get_name(self):
        for characteristic in self.characteristics:
            if isinstance(characteristic, NameCharacteristic):
                return characteristic.value
        return None
"""

Accessory should be created as:

"""
    accessory = homekit.model.Accessory(accessory_name, 'Nevo', 'HisenseTV', '0001', '0001')
    service = TVService(accessory_name, 'Nevo', 'HisenseTV', '0001', '0001')
    service.characteristics[-2].set_get_value_callback(get_state_function)
    service.characteristics[-2].set_set_value_callback(set_state_function)
    accessory.services.append(service)
"""

get_state_function - returns 0 if off, 1 if on
set_state_function(value) - value=1 if power on action is taken, 0 if power off action

is it possible to add as example for future reference for others?

**Comment by jlusiardi** [comment]
Hi, 

you could do a pull request and put `ActiveCharacteristic` into homekit/model/characteristics/active.py, `ActiveIdentifierCharacteristic` into  homekit/model/characteristics/active_identifier.py and `TVService` into homekit/model/services/tv_service.py. The accessory code could go into /demo_tv.py. 

That would be great. 
Joachim

**Comment by nevoomer** [comment]
done
