### ISSUE TITLE
Remove pairing does not work

### ISSUE THREAD

**Issue by kvaellning** [jlusiardi/homekit_python#223]
(using a BLE accessory)

On calling `remove_pairing`, a BleSession is set up directly passing formerly extracted `pairing_data`. This results in an error when while treating `pairing_data` as a dictionary and trying to access the key _accessories_ .

Adding a breakpoint to the `BleSession` init-function, it appears to be never called otherwise (but I currently checked only `identify_ble`).

From what I see around here, accessing this `accessory`-key doesn't make much sense to me either, since the session is established to only one device.

Does anybody now why it is present, and if it can be safely deleted?

**Comment by Jc2k** [comment]
I am a little rusty on the BLE side but the gist of the situation is:

IP was added first, then BLE was added. So the API is framed around IP, and IP is the most extensively tested. So it's important to note that an IP pairing is always comprised of accessories, even if the list only contains 1 item. So the API is built around 1 pairing having multiple accessories. In the case of Hue, aid 1 is the Hub and then there is an accessory for each bulb.

The API is framed around IP and using `aid` and `iid` to poll. We need the schema data to map (aid, iid) to the BLE characteristic. So it's stored in the `accessories` key.

Getting a "schema" of the characteristics, services, the iid's, sid's etc, is expensive on BLE. So we use a cached copy in the `accessories` key.

Right now this key is populated by `list_accessories_and_characteristics`.

`remove_pairing` likely needs the schema to resolve `CharacteristicsTypes.PAIRING_PAIRINGS`.

**Comment by kvaellning** [comment]
Thanks for the background information. I will take a look in the difference between IP and BLE, maybe the pairing data for BLE is missing some fields (so it appears).

**Comment by Jc2k** [comment]
In particular, calling `list_accessories_and_characteristics` should populate the `accessories` key, I thought it was called implicitly but it might not be. Certainly when that code was first added it would call `list_accessories_and_characteristics` as part of the pairing process, then store the result in the pairing file.

**Comment by jlusiardi** [comment]
The historic process of implementation was:

1. Create an IP Accessory so that an iPhone can connect and control it
2. Create controller for IP Accessories
3. Implement BLE on controller side as well (BLE is my weakest  point of knowledge to be honest)
