### ISSUE TITLE
Add homekit_python controller to an existing homekit "Home"

### ISSUE THREAD

**Issue by danricho** [jlusiardi/homekit_python#240]
Hi,

I have a few HomeKit accessories which are paired to my exiting HomeKit "Home" which we can use via my iPhone or my wife's iPhone and access remotely via our AppleTV.

I'm wondering whether this library is able to integrate into this existing system to allow for python scripted automation.
I'd be fine running it as a separate system, however some accessories can't be paired to the `homekit_python` controller without unpairing from the existing system.

Thanks for any guidance!

**Comment by jlusiardi** [comment]
In theory https://github.com/jlusiardi/homekit_python#add_additional_pairing might help. Big but ahead: this will only work if you are able to extract the public key from the existing controller. I tested this only with two different instances of the python implementation as controller.

The Apple devices use a mechanism for sharing those keys that is not defined in HomeKit (afaik at least).

**Comment by danricho** [comment]
I assume that would only be via a MacOS device [like on this page](https://pvieito.com/2019/12/extract-homekit-pairing-keys)... which unfortunately rules me out as I don't have a Mac! 

How annoying. Thanks for the fast reply!

**Comment by jlusiardi** [comment]
Oh another obstacle, you would need more of a way to tell the iPhone/AppleTV something like "here is a public key from some controller, please add it" because your accessories are already paired with the official HomeKit implementation...

**Comment by danricho** [comment]
Is there a work around by pairing to the python controller before pairing to the Apple Controller? 
If not, how do people generally use the controller with native HomeKit accessories?

**Comment by jlusiardi** [comment]
I am not aware of any workaround. The main focus of this project was/is to offer a way to
 - implement accessories in python and/or
 - control accessories paired to controller written in python

**Comment by danricho** [comment]
No problem. It's a great project. And thanks so much for the quick guidance. 

Maybe with the upcoming Matter Standard being integrated with HomeKit more options will present themselves!

In the meantime I will be emulating some accessories in Python.

Have a great day.

**Comment by jlusiardi** [comment]
Thank you :)

**Comment by Jc2k** [comment]
You can use home assistant here. You add your devices to home assistant then add home assistant to the Home app on your phone. So each device is only paired once. Home Assistant acts as a proxy, and it can run your automations. But you can still use the Home app and Siri.

It's not perfect but it works well enough for me.

**Comment by danricho** [comment]
@Jc2k Yeh I was looking more for a small side connection to HomeKit itself... I also use homebridge and have previously used openhab. 
I didn't realize home assistant integrated so well to HomeKit. Thanks for the suggestion!

I'm not convinced I need another system for the sake of python automation, but I'll definitely have a look.
