### ISSUE TITLE
Cannot connect my insignia smart plugs

### ISSUE THREAD

**Issue by kzaoaai** [jlusiardi/homekit_python#34]
I was successful with leviton dimmers, however this won't work. I get:

Jun 10 02:46:32 hassbian hass[22096]: 2018-06-10 02:46:32 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall configurator.configure: fields=code=309-96-501, configure_id=1672433776-1>
Jun 10 02:46:32 hassbian hass[22096]: Traceback (most recent call last):
Jun 10 02:46:32 hassbian hass[22096]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/core.py", line 1007, in _event_to_service_call
Jun 10 02:46:32 hassbian hass[22096]:     await service_handler.func(service_call)
Jun 10 02:46:32 hassbian hass[22096]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/configurator.py", line 224, in async_handle_service_call
Jun 10 02:46:32 hassbian hass[22096]:     call.data.get(ATTR_FIELDS, {}))
Jun 10 02:46:32 hassbian hass[22096]:   File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
Jun 10 02:46:32 hassbian hass[22096]:     yield self  # This tells Task to wait for completion.
Jun 10 02:46:32 hassbian hass[22096]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
Jun 10 02:46:32 hassbian hass[22096]:     future.result()
Jun 10 02:46:32 hassbian hass[22096]:   File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
Jun 10 02:46:32 hassbian hass[22096]:     raise self._exception
Jun 10 02:46:32 hassbian hass[22096]:   File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Jun 10 02:46:32 hassbian hass[22096]:     result = self.fn(*self.args, **self.kwargs)
Jun 10 02:46:32 hassbian hass[22096]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/homekit_controller/__init__.py", line 161, in device_config_callback
Jun 10 02:46:32 hassbian hass[22096]:     self.accessory_setup()
Jun 10 02:46:32 hassbian hass[22096]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/homekit_controller/__init__.py", line 112, in accessory_setup
Jun 10 02:46:32 hassbian hass[22096]:     data = json.loads(response.read().decode())
Jun 10 02:46:32 hassbian hass[22096]:   File "/usr/lib/python3.5/http/client.py", line 461, in read
Jun 10 02:46:32 hassbian hass[22096]:     s = self._safe_read(self.length)
Jun 10 02:46:32 hassbian hass[22096]:   File "/usr/lib/python3.5/http/client.py", line 609, in _safe_read
Jun 10 02:46:32 hassbian hass[22096]:     raise IncompleteRead(b''.join(s), amt)
Jun 10 02:46:32 hassbian hass[22096]: http.client.IncompleteRead: IncompleteRead(0 bytes read, 845 more expected)

**Comment by jlusiardi** [comment]
Hello,

so i see you are using it via homeassistant. Which version does this use? Can you try to connect via the command line tools i deliver with homekit_python like:
 * discover
 * pair
 * get_accessories
 * ...

Perhaps the responses of the insignia smart plugs are not what i expected.

Cheers
Joachim

**Comment by mjg59** [comment]
I think this is probably the same as #37

**Comment by jlusiardi** [comment]
Yepp, i would like to have feedback from @kzaoaai :)

**Comment by mjg59** [comment]
@kzaoaai This should be fixed in the current git code

**Comment by jlusiardi** [comment]
Close due to lack of feedback.
