### ISSUE TITLE
Incomplete reads from chunked data

### ISSUE THREAD

**Issue by mjg59** [jlusiardi/homekit_python#37]
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/hap/lib/python3.5/site-packages/homekit/unpair.py", line 48, in <module>
    data = response.read()
  File "/usr/lib/python3.5/http/client.py", line 461, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.5/http/client.py", line 609, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(0 bytes read, 6 more expected)
```
_read_response() shows a 96 byte read with a chunk length of 78 bytes (so a complete read), which only contains the headers. If I remove the break statement and allow the loop to continue, performing another read gives an 18 byte read with a length value of 6, and performing another read gives the remaining 6 bytes. Further reads receive no data.

**Comment by mjg59** [comment]
[tcpdump.zip](https://github.com/jlusiardi/homekit_python/files/2157495/tcpdump.zip)

tcpdump attached - this is with the break statement from the end of the while True: loop in _read_response() removed in order to ensure that everything is read.

**Comment by mjg59** [comment]
I /think/ we need to do this by parsing the content-length header, but that seems awkward to fit into the existing framework.

**Comment by mjg59** [comment]
https://github.com/jlusiardi/homekit_python/pull/38 works, but doesn't seem super appealing.

**Comment by mjg59** [comment]
https://github.com/jlusiardi/homekit_python/commit/e6bf51eb4630d5bca3a876b2ac502b5b7169eaa0 fixes this.

**Comment by mjg59** [comment]
(Any chance you can cut a 0.10 with this? It ought to fix a bunch of Home Assistant bugs)

**Comment by jlusiardi** [comment]
@mjg59 will do this ;) this will be mostly as a controller? What do u think about https://raw.githubusercontent.com/jlusiardi/homekit_python/expose_controller_api/doc/controller.png ?

**Comment by jlusiardi** [comment]
done the release

**Comment by mjg59** [comment]
I'm out of town at the moment, I'll give it a go at the weekend.
