### ISSUE TITLE
Pairing doesn't appear to work on Raspberry PI

### ISSUE THREAD

**Issue by maccoylton** [jlusiardi/homekit_python#4]
Running on Raspberry PI, I get a bad BadRequest 400 response from my accessory when I try to pair, which I found by running through PuDB. Any ideas ?

**Comment by jlusiardi** [comment]
hi,

what commands do you execute in detail? what role does PuDB play?

**discover.py** shows your accessory?

which step of **pair.py** fails?

Greetings Joachim

**Comment by maccoylton** [comment]
discover.py see the devices. PuDB is a debugger that allows me to step through the code, when it send the first request to the accessory, I can see using the debugger it get back a bad request response, it fails at the asset statement that follow the response.

**Comment by jlusiardi** [comment]
can you give me the output of **discover.py** for the device?

does PuDB enable you to give me the complete request and response of the first request of **pair.py**?
