### ISSUE TITLE
Request: Better Documentation for creating services

### ISSUE THREAD

**Issue by jslay88** [jlusiardi/homekit_python#5]
I have tried to create my own services by going through the source code.

I created my own characteristics classes with the needed type, perms, formats and values, and created my own service with those.

Everything loads fine, and the accessory shows up on the devices, but cannot successfully pair. 

Also, can you provide the source to the documentation you provide the page numbers to in your source? I have searched everywhere for HomeKit documentation that is paged.

**Comment by jlusiardi** [comment]
Hello,

the page numbers refer to Apple's HomeKit Accessory Protocol Specification (Non-Commercial Version) in Release R1. I doubt I am allowed to distribute. The link is https://developer.apple.com//homekit/specification/ (Apple ID required).

Can you give me more details about what you are trying to do?

Regards
Joachim
