### ISSUE TITLE
Resolve dependency issues with getsenic/gatt-python

### ISSUE THREAD

**Issue by jlusiardi** [jlusiardi/homekit_python#61]
At the moment we have a patched version of getsenic/gatt-python in the staging folder. This is a blocker for Home Assistant integration. 

Possible Options:
- have the PR merged (https://github.com/getsenic/gatt-python/pull/36)
- ship a fork of getsenic/gatt-python under homekit/gatt
- subclass code with descriptor and leave upstream untouched

**Comment by Jc2k** [comment]
I’ll put together a PR for option 3 and see what it looks like.

**Comment by jlusiardi** [comment]
not more of `staging-gatt` is left, so I close this.
