### ISSUE TITLE
What is right way to bootstrap the alias file?

### ISSUE THREAD

**Issue by Jc2k** [jlusiardi/homekit_python#85]
```
$ python -m homekit.pair_ble -f test-alias -a energy -m 00:00:00:00:00:00 -p 123-45-678 --log DEBUG
Could not open "test-alias" because it does not exist
```

As a dev i know I can just make an empty file with `{}` in it. We should probably make this less of a UX papercut? How about it asks you y/n if you want to make that file, with an optional `-c` flag to always create file if it doesnt exist?

**Comment by jlusiardi** [comment]
We could add a little tool that just creates this empty file and simply refer to it in the error message.

Since this is independent to ble, I would happily accepted a PR to master 😉

**Comment by Jc2k** [comment]
Hmm it would probably end up conflicting with the bluetooth branch 😢

**Comment by jlusiardi** [comment]
one step after another...
