### ISSUE TITLE
Add flake8 to travis build

### ISSUE THREAD

**Issue by Jc2k** [jlusiardi/homekit_python#86]
I use flake8 a lot on my own python projects. If you've not seen it before its a linting tool. There are some good checks in there we could use:

 * Imports that are made but not used
 * Things that are used but not imported
 * Variables that are used by not assigned
 * Variables that are assigned but then not used
 * Identation errors (tabs vs spaces, not a multiple of 4 etc)
 * And more...

There are some style/cosmetic checks where it encourages you to follow pep8. Some people find these annoying. It looks like homekit_python's coding style is closely aligned with flake8 anyway so the majority of checks that fail are things I would probably want to change. (Some projects it has been really painful to enable on because of large numbers of stylistic/cosmetic disagreements).

I would be happy to put together a PR for this if its interesting, if not feel free to close immediately. If you do want to try it, its probably something to do when add_bluetooth is ready to merge to master. It would be difficult to do while we have 2 long running branches probably.

**Comment by jlusiardi** [comment]
Yeah sure, sounds like a tool helping to improve the code quality!

**Comment by jlusiardi** [comment]
Hey,

my latest code in `add_bluetooth` should already comply with this flake8 config. I just adjusted the handling of some import stuff:
```
[flake8]
max-line-length = 120
statistics = True
; F401  module imported but unused
; F403  ‘from module import *’ used; unable to detect undefined names
; F405  name may be undefined, or defined from star imports: module
ignore=F401,F403,F405
```

Do you think that's ok?

**Comment by Jc2k** [comment]
Nice!

I'm guessing most of the ignores are because of __init__.py stuff? I've managed to run it on fairly large projects without those (didn't want it to miss any undefined names). The trick to stopping those is to define an `__all__` list.

For example if you had an `__init__.py` that looks like:

```
from homekit.controller import Controller
from homekit.accessoryserver import AccessoryServer
```

Then to stop the error you can:

```
from homekit.controller import Controller
from homekit.accessoryserver import AccessoryServer

__all__ = [
    'AccessoryServer',
    'Controller',
]
```

The __all__ list is actually used by the wildcard importer (it will only import stuff in the list, falling back to everything when __all__ isnt defined). It's also a convention about defining what your public API is - which classes and functions your exporting from that module.

A lot of devs frown on wildcard imports these days because they make it harder for linters and code completion and other dev tools to do a good job. But thats obviously quite annoying for us when we want to do this:

```
from homekit.exceptions import *
```

Really it comes down to personal taste.

**Comment by jlusiardi** [comment]
integrated to add_bluetooth
