### ISSUE TITLE
Problem with setup.py on some but not all pythons

### ISSUE THREAD

**Issue by Jc2k** [jlusiardi/homekit_python#87]
A HA user has reported an issue with the homekit 0.12.0 release:

https://github.com/home-assistant/home-assistant/issues/20115

```
$ pip3 --no-cache-dir install homekit==0.12.0
Collecting homekit==0.12.0
  Downloading https://files.pythonhosted.org/packages/1d/a5/f7cb393652053ad3a40f503f1b3f444c56b2f30dfcea913beccfcace7220/homekit-0.12.0.tar.gz (56kB)
    100% |################################| 61kB 2.6MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-q0ru5r5i/homekit/setup.py", line 21, in <module>
        long_description = fh.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7967: ordinal not in range(128)
```

Using `sdist` rather than the wheel. It's a Debian Stretch box with python 3.5.

Can't recreate on python3.6 / bionic (where im working on homekit stuff) or in a python:3.5 container.

**Comment by jakeapp** [comment]
same issue here... python 3.5 on Debian Stretch based system...  cloning the repo and commenting out lines: 20,21;49,50  in setup.py allowed for trouble free install...

**Comment by jlusiardi** [comment]
First hint tells me, that the TRÅDFRI is the problem (especially Å):
```
git clone https://github.com/jlusiardi/homekit_python.git
git checkout 0.12.0
content=`cat README.md `
echo ${content:7965:5} | hexdump -C
```
result:
```
00000000  54 52 c3 85 44 0a                                 |TR..D.|
00000006
```

**Comment by Jc2k** [comment]
I couldn't get it to fail on a python:3.5 container. There i did this:

```
$ python3
>>> import locale
>>> locale.getpreferredencoding() 
'UTF-8'
>>> 
```

Apparently that is the default encoding that open will use - if that is returning something else on your environment that fails then passing encoding to open is the right fix. It's probably 'right' to pass utf-8 in top open() as we know README is valid utf-8, i guess.

**Comment by jlusiardi** [comment]
ah, in the docker container it is "'ANSI_X3.4-1968'"

**Comment by Jc2k** [comment]
It’s the same encoding the HA user is reporting! So explicit encoding in setup.py should fix it! 😃
