### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by mjg59** [jlusiardi/homekit_python#9]
I'd like to use this module to add Homekit integration to home-assistant.io, but there's currently no license in the repository so I'm unable to. Would it be possible to add an explicit license?

**Comment by jlusiardi** [comment]
mh good point. i have never really thought about which one to use and so i'm pretty unsure.

What would match home-assistent's license best?

**Comment by mjg59** [comment]
Apache License version 2.0 (https://www.apache.org/licenses/LICENSE-2.0) is probably the easiest

**Comment by jlusiardi** [comment]
yeah but shouldn't there be a license statement in every file? See https://www.apache.org/licenses/LICENSE-2.0#apply ?

**Comment by mjg59** [comment]
Ideally, but it's not uncommon for projects to just carry a single license file

**Comment by jlusiardi** [comment]
Would this fix your needs?

https://github.com/jlusiardi/homekit_python/tree/add_license

**Comment by mjg59** [comment]
Thanks!
