### ISSUE TITLE
PR #92 introduced issues with the tests

### ISSUE THREAD

**Issue by jlusiardi** [jlusiardi/homekit_python#93]
The function `hci_adapter_exists_and_supports_bluetooth_le` is breaking the tests. 

I tried to work around that with a mock in `ble_controller_test.py`:

```python
...
@mock.patch('homekit.controller.tools.hci_adapter_exists_and_supports_bluetooth_le', return_value=True)
class TestBLEController(unittest.TestCase):

    def test_discovery(self, mock1):
        ...
```

But this only gets used when I change the code under test form 
```python
from homekit.controller.tools import hci_adapter_exists_and_supports_bluetooth_le
...
        if not hci_adapter_exists_and_supports_bluetooth_le(adapter):
            raise BluetoothAdapterError('Adapter "{a}" does not suit our needs'.format(a=adapter))
...
```

to (in my eyes ugly):
```python
import homekit
...
        if not homekit.controller.tools.hci_adapter_exists_and_supports_bluetooth_le(adapter):
            raise BluetoothAdapterError('Adapter "{a}" does not suit our needs'.format(a=adapter))
...
```

@Jc2k: can you help?

**Comment by Jc2k** [comment]
Yes! So the issue is that you are patching the place where the object is defined not where it is imported. But the mock is applied after imports have happened. So the code you are trying to test still has the unmocked version.

Try mocking homekit.controller.ble_impl hci_adapter_exists_and_supports_bluetooth_le?

**Comment by Jc2k** [comment]
I would probably do the test and exception in our subclass of DeviceManager though (homekit.controller.ble_impl.device) - has the same effect but there is less code duplication and also you won’t need to mock it as the tests already mock DeviceManager!

**Comment by Jc2k** [comment]
I noticed you switched away from assert in a recent commit. Note that in pytest assert is considered more normal than unittest asserts.

https://docs.pytest.org/en/latest/assert.html

**Comment by jlusiardi** [comment]
ok found out it needs to be `@mock.patch('homekit.controller.controller.hci_adapter_exists_and_supports_bluetooth_le', return_value=True)` at least for the first test.

But I consider your proposal to move the check to our subclass of DeviceManager.

BTW: is there any way to discuss things (also open & transparent) but not in issues? E.g. wether to use pytest instead on unittest from above will soon get lost here i fear.

**Comment by Jc2k** [comment]
I was wondering the same myself. I use Gitter for another GitHub project (vmware_exporter) and thats OK. I've also got a few slacks so would be OK joining another one of those if it was appropriate. Homeassistant have a discord which I was considering joining to try and help a few homekit users over there. I used to be on FreeNode and OFTC but rarely check theses days. Gitter and Slack can both send my e-mails if i miss something.

**Comment by Jc2k** [comment]
Gitter does - you can see the vmware_exporter one here https://github.com/pryorda/vmware_exporter/blob/master/README.md - there is a badge that links to it and you can read without signing up. I don’t know how usable it is with a large chat history we’ve only just started using it.

Slack is probably the most closed and wouldn’t go that way.

Discord works in browser too and there is a persistent history but you have to be signed in I think. You could join the home assistant one to get a feel if what it’s like. It’s meant for gamers so has voice chat and stuff but I know a few large non gamer communities (like homeassistant) use it.

**Comment by jlusiardi** [comment]
Tests are green again
